#!/bin/sh

# REQUIRE: DAEMON
# PROVIDE: nbr_adv
# KEYWORD: shutdown

export PATH=/usr/local/bin:$PATH

. /etc/rc.subr

name="nbr_adv"
rcvar="${name}_enable"

load_rc_config ${name}
: ${nbr_adv_enable:=no}
: ${nbr_adv_wan_if:=''}
: ${nbr_adv_lan_if:=''}
: ${nbr_adv_north_rt_addr:=''}

pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-c -t ${name} -S -T ${name} -P ${pidfile} /opt/ra-support/bin/nbr-adv --wan-if ${nbr_adv_wan_if} --lan-if ${nbr_adv_lan_if} --north-rt-addr ${nbr_adv_north_rt_addr}"

run_rc_command "$1"
