#!/bin/sh

# REQUIRE: DAEMON
# PROVIDE: ra_transform
# KEYWORD: shutdown

export PATH=/usr/local/bin:$PATH

. /etc/rc.subr

name="ra_transform"
rcvar="${name}_enable"

load_rc_config ${name}
: ${ra_transform_enable:=no}

pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-c -r -t ${name} -S -T ${name} -P ${pidfile} /opt/ra-support/bin/ra-transform"

run_rc_command "$1"
