#!/bin/sh

# REQUIRE: DAEMON
# PROVIDE: lanrtr_rtsol
# KEYWORD: shutdown

export PATH=/usr/local/bin:$PATH

. /etc/rc.subr

name="lanrtr_rtsol"
rcvar="${name}_enable"

load_rc_config ${name}
: ${lanrtr_rtsol_enable:=no}
: ${lanrtr_rtsol_iface:=''}
: ${lanrtr_rtsol_script:=''}
: ${lanrtr_rtsol_north_rt_addr:=''}

extra_commands=reload

pidfile="/var/run/${name}.pid"
pidfile_actual="/var/run/${name}.actual.pid"
command="/usr/sbin/daemon"
command_args="-c -t ${name} -S -T ${name} -P ${pidfile} -p ${pidfile_actual} /usr/local/bin/lanrtr-rtsol -i ${lanrtr_rtsol_iface} -s ${lanrtr_rtsol_script} --north-rt-addr ${lanrtr_rtsol_north_rt_addr}"
reload_cmd="lanrtr_rtsol_reload"

lanrtr_rtsol_reload()
{
    kill -s SIGUSR1 $(cat ${pidfile_actual})
}

run_rc_command "$1"
